name: "publish"

on:
  push:
    branches:
      - "3.20"

jobs:
  build-and-publish-image:
    runs-on: "ubuntu-latest"
    permissions:
      contents: "read"
      packages: "write"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "c032/gha-docker@main"
        with:
          image-name: "${{ github.repository }}"
          registry-username: "${{ github.actor }}"
          registry-password: "${{ secrets.GITHUB_TOKEN }}"
